version = 0.1

[dev.deploy.parameters]
profile = "default"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
stack_name = "library-stack"
s3_prefix = "library"
s3_bucket = "my-function-bucket-for-lambda"
region = "eu-west-1"
parameter_overrides = "apiStage=\"dev\" tableName=\"library-table\"" 

[dev.local_invoke.parameters]
env_vars = "env.json"