AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: ApiGateway to DynamoDb

Parameters:
  apiStage:
    Type: String
    Description: stage used to deploy the API
    Default: dev
  tableName:
    Type: String
    Description: name of the dynamoDB table
    Default: TableName
  responseMappingTemplateDef:
    Type: String
    Description: |
      utility definition used in most response mapping templates.
      Parses the item recieved from DynamoDB in a more JSON friendly form.
      Do not override unless you know what you are doing
    Default: |
      #define( $DDBAttributeParser )
        #foreach($entry in $item.entrySet())
          #if($entry.value.S && $entry.value.S != "")
            "$entry.key": "$entry.value.S"
          #elseif($entry.value.B && $entry.value.B != "")
            "$entry.key": "$entry.value.B"
          #elseif($entry.value.NULL && $entry.value.NULL != "")
            "$entry.key": null
          #elseif($entry.value.NS && $entry.value.NS != "")
            "$entry.key": [
            #foreach($value in $entry.value.NS)
              $value #if($foreach.hasNext),#end
            #end
            ]
          #elseif($entry.value.M && $entry.value.M != "")
            "$entry.key": $input.json("$.Item.${entry.key}")
          #else
            "$entry.key": $entry.value.values().toArray()[0]
          #end
          #if($foreach.hasNext),#end
        #end
      #end


Resources:

  ApiGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ApiGatewayDynamoDBCRUDRole
      Description: Role assumed by the ApiGateway - allows basic CRUD operation on DynamoDB
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action:
              - sts:AssumeRole

  DynamoDBCRUDPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: DynamoDBCRUDPolicy
      Roles:
        - !Ref ApiGatewayRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "DynamoDBCRUDPolicy"
            Effect: "Allow"
            Resource: 
              - !GetAtt DynamoDB.Arn
              - !Sub "${DynamoDB.Arn}/index/*"
            Action:
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:PutItem
              - dynamodb:DeleteItem
              - dynamodb:GetItem
              - dynamodb:Scan
              - dynamodb:Query
              - dynamodb:UpdateItem

  DynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref tableName
      AttributeDefinitions: 
        - AttributeName: pk
          AttributeType: "S"
        - AttributeName: sk
          AttributeType: "S"
        - AttributeName: fk
          AttributeType: "S"
      KeySchema: 
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI_1
          KeySchema:
            - AttributeName: sk
              KeyType: HASH
            - AttributeName: pk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: GSI_2
          KeySchema:
            - AttributeName: fk
              KeyType: HASH
            - AttributeName: pk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: gateway
      StageName: !Ref apiStage
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./swagger.yaml

Outputs:
  ApiGateway:
    Description: "API Gateway endpoint URL for ${apiStage}"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${apiStage}/"

